### ISSUE TITLE
Error: adapting config using caddyfile: Caddyfile:2: unrecognized directive: secret_id

### ISSUE THREAD

**Issue by wangzexi** [caddy-dns/tencentcloud#2]
I've been struggling for two hours, can you give me some advice?😟

```
Error: adapting config using caddyfile: Caddyfile:2: unrecognized directive: secret_id
```

```Dockerfile
FROM caddy:2-builder AS builder

RUN go env -w GOPROXY=https://goproxy.cn,direct && \
    xcaddy build --with github.com/caddy-dns/tencentcloud

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

```
version: "3"

services:

  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - TENCENTCLOUD_SECRET_ID=123456
      - TENCENTCLOUD_SECRET_KEY=37743fbf76ad143fbf3643fbf33ca43fbf
```

```Caddyfile
acme_dns tencentcloud {
    secret_id {env.TENCENTCLOUD_SECRET_ID}
    secret_key {env.TENCENTCLOUD_SECRET_KEY}
}
```
